name = "voidherob2"
[observability]
enabled = true

compatibility_date = "2024-09-26"
main = "index.js"

[vars]
B2_APPLICATION_KEY_ID = "003481963253c050000000001"
B2_APPLICATION_KEY = 'K003YXH4vky/E+C4rN3k1sb+P/lgi70'
B2_ENDPOINT = "https://s3.eu-central-003.backblazeb2.com"
BUCKET_NAME = "voidhero"
ALLOW_LIST_BUCKET = "true"
